packages:
  - 'apps/*'

catalogs:
  css:
    class-variance-authority: ^0.7.1
    clsx: ^2.1.1
  db:
    '@types/pg': ^8.15.5
    bcrypt-ts: ^7.1.0
    drizzle-kit: ^0.31.4
    drizzle-orm: ^0.44.4
    pg: ^8.16.3
  dev:
    '@antfu/ni': ^25.0.0
    '@types/node': ^20.11.17
    dotenv: ^16.5.0
    tsx: ^4.20.4
    typescript: ^5.8.3
    typestep: ^0.5.2
  hono:
    '@hono/node-server': ^1.18.2
    '@hono/trpc-server': ^0.4.0
    hono: ^4.8.12
  lint:
    '@antfu/eslint-config': ^4.14.1
    eslint: ^9.28.0
  log:
    pino: ^9.7.0
    pino-pretty: ^13.0.0
  tailwind:
    '@tailwindcss/vite': ^4.1.12
    tailwind-merge: ^3.3.1
    tailwindcss: ^4.1.12
    tw-animate-css: ^1.3.6
  test:
    '@playwright/test': ^1.53.2
  trpc:
    '@trpc/client': ^11.4.4
    '@trpc/server': ^11.4.4
  vite:
    '@julr/vite-plugin-validate-env': ^2.2.0
    vite: ^6.3.5
  vue:
    '@vitejs/plugin-vue': ^5.2.4
    '@vueuse/core': ^13.3.0
    lucide-vue-next: ^0.517.0
    reka-ui: ^2.3.1
    vee-validate: ^4.15.1
    vue: ^3.5.18
    vue-router: ^4.5.1
    vue-sonner: ^2.0.2
    vue-tsc: ^2.2.12
  zod:
    '@vee-validate/zod': ^4.15.1
    zod: ^3.25.76
