catalogMode: prefer
cleanupUnusedCatalogs: true

shellEmulator: true
trustPolicy: no-downgrade

packages:
  - 'apps/*'

catalogs:
  auth:
    better-auth: ^1.4.5
  css:
    class-variance-authority: ^0.7.1
    clsx: ^2.1.1
  db:
    '@types/pg': ^8.15.6
    bcrypt-ts: ^8.0.0
    drizzle-kit: ^0.31.8
    drizzle-orm: ^0.44.7
    knex: ^3.1.0
    pg: ^8.16.3
  dev:
    '@types/node': ^20.11.17
    dotenv: ^17.2.3
    tsx: ^4.21.0
    typescript: ^5.8.3
    typestep: ^0.5.2
  hono:
    '@hono/node-server': ^1.19.6
    '@hono/trpc-server': ^0.4.1
    hono: ^4.10.7
  lint:
    '@antfu/eslint-config': ^6.4.2
    eslint: ^9.39.1
  log:
    pino: ^10.1.0
    pino-pretty: ^13.1.3
  tailwind:
    '@tailwindcss/vite': ^4.1.17
    tailwind-merge: ^3.4.0
    tailwindcss: ^4.1.17
    tw-animate-css: ^1.4.0
  test:
    '@playwright/test': ^1.57.0
  trpc:
    '@trpc/client': ^11.7.2
    '@trpc/server': ^11.7.2
  vite:
    '@julr/vite-plugin-validate-env': ^2.2.0
    vite: ^7.2.6
  vue:
    '@vitejs/plugin-vue': ^6.0.2
    '@vueuse/core': ^14.1.0
    lucide-vue-next: ^0.555.0
    reka-ui: ^2.6.1
    vee-validate: ^5.0.0-beta.0
    vue: ^3.5.25
    vue-router: ^4.6.3
    vue-sonner: ^2.0.9
    vue-tsc: ^2.2.12
    vue-i18n: ^11.2.2
  zod:
    zod: ^4.1.13
