packages:
  - 'apps/*'

catalogs:
  css:
    class-variance-authority: ^0.7.1
    clsx: ^2.1.1
  db:
    '@types/pg': ^8.15.6
    bcrypt-ts: ^7.1.0
    drizzle-kit: ^0.31.6
    drizzle-orm: ^0.44.7
    pg: ^8.16.3
  dev:
    '@antfu/ni': ^25.0.0
    '@types/node': ^20.11.17
    dotenv: ^16.6.1
    tsx: ^4.20.6
    typescript: ^5.9.3
    typestep: ^0.5.2
  hono:
    '@hono/node-server': ^1.19.5
    '@hono/trpc-server': ^0.4.0
    hono: ^4.10.4
  lint:
    '@antfu/eslint-config': ^4.14.1
    eslint: ^9.39.0
  log:
    pino: ^9.14.0
    pino-pretty: ^13.1.2
  tailwind:
    '@tailwindcss/vite': ^4.1.16
    tailwind-merge: ^3.3.1
    tailwindcss: ^4.1.16
    tw-animate-css: ^1.4.0
  test:
    '@playwright/test': ^1.56.1
  trpc:
    '@trpc/client': ^11.6.0
    '@trpc/server': ^11.6.0
  vite:
    '@julr/vite-plugin-validate-env': ^2.2.0
    vite: ^6.4.1
  vue:
    '@vitejs/plugin-vue': ^5.2.4
    '@vueuse/core': ^13.9.0
    lucide-vue-next: ^0.548.0
    reka-ui: ^2.6.0
    vee-validate: ^4.15.1
    vue: ^3.5.22
    vue-router: ^4.6.3
    vue-sonner: ^2.0.9
    vue-tsc: ^2.2.12
  zod:
    '@vee-validate/zod': ^4.15.1
    zod: ^3.25.76
