packages:
  - 'apps/*'

catalogs:
  db:
    "@types/pg": "^8.15.4"
    "drizzle-kit": "^0.31.1"
    "drizzle-orm": "^0.44.2"
    "pg": "^8.16.1"
    "bcrypt-ts": "^7.1.0"
  css:
    class-variance-authority: ^0.7.1
    clsx: ^2.1.1
  log:
    "pino-pretty": "^13.0.0"
    "pino": "^9.7.0"
  dev:
    '@antfu/ni': ^25.0.0
    '@types/node': ^20.11.17
    tsx: ^4.7.1
    typescript: ^5.8.3
    "dotenv": "^16.5.0"
    "typestep": "^0.5.2"
  hono:
    '@hono/node-server': ^1.14.4
    '@hono/trpc-server': ^0.3.4
    hono: ^4.7.11
  lint:
    '@antfu/eslint-config': ^4.14.1
    eslint: ^9.28.0
  tailwind:
    '@tailwindcss/vite': ^4.1.10
    tailwind-merge: ^3.3.1
    tailwindcss: ^4.1.10
    tw-animate-css: ^1.3.4
  trpc:
    '@trpc/client': ^11.4.2
    '@trpc/server': ^11.4.2
  vite:
    '@julr/vite-plugin-validate-env': ^2.1.0
    vite: ^6.2.4
  vue:
    '@vitejs/plugin-vue': ^5.2.3
    '@vueuse/core': ^13.3.0
    lucide-vue-next: ^0.517.0
    reka-ui: ^2.3.1
    vue: ^3.5.13
    vue-router: ^4.5.0
    vue-tsc: ^2.2.8
    "vue-sonner": "^2.0.1"
    "vee-validate": "^4.15.1"
  zod:
    zod: ^3.25.67
    "@vee-validate/zod": "^4.15.1"
  test:
    "@playwright/test": "^1.53.2"
