name: Playwright Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    # skip the job for now
    if: false
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps
        working-directory: apps/frontend

      - name: Run Playwright tests
        run: pnpm test:e2e
        working-directory: apps/frontend

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
